### ISSUE TITLE
Establish initial write permissions

### ISSUE THREAD

**Issue by ijmitch** [openmainframeproject/wg-modernization#1]
@jmertic - (somewhat duplicating what I said in Jira) I'd like to have myself and Misty Decker to have write permissions initially, and also to turn on branch protection for `main` with a demand for PRs to be reviewed before merging.

Thanks

**Comment by jmertic** [comment]
Hi @ijmitch - I invited you now. Once you accept the invitation I can give you access to manage adding people to the team for managing who has maintainer access.

https://github.com/orgs/openmainframeproject/teams/modernization-wg/members

**Comment by ijmitch** [comment]
Thanks @jmertic ... invitation received and accepted.

**Comment by ijmitch** [comment]
Great... now have access to `settings` so can progress the set up.

**Comment by ijmitch** [comment]
@jmertic my settings options don't include setting up branch protection rules, and my #2 PR isn't demanding a review so I assume the option for reviews to be mandatory isn't in place.

**Comment by jmertic** [comment]
I can set those up - what are your preferences?

**Comment by ijmitch** [comment]
<img width="764" alt="image" src="https://user-images.githubusercontent.com/1266441/210799480-5d267b5d-59f2-4429-a010-0d6fcaf3d74c.png">

on `main` please.

**Comment by jmertic** [comment]
Done - sorry about that!

**Comment by jmertic** [comment]
Anything else needed here? Else we can close
