### ISSUE TITLE
Adding participants to the project

### ISSUE THREAD

**Issue by ijmitch** [openmainframeproject/wg-modernization#7]
@jmertic ... I attempted to add Rick Perret to the project via https://github.com/orgs/openmainframeproject/teams/modernization-wg/members but it's complaining Rick's not a member of the organisation.

**Comment by ijmitch** [comment]
am I going about this in the wrong way?

**Comment by jmertic** [comment]
Hey - what's Rick's GH id?

**Comment by ijmitch** [comment]
rpomp

**Comment by jmertic** [comment]
I fixed your permissions and sent an invite to Rick now - should be better going forward

**Comment by ijmitch** [comment]
Many thanks @jmertic ... and I managed to send an invitation to Misty.
